[build]
  # Since this is a static HTML site, no build command needed
  publish = "."

[build.environment]
  # No build environment needed for static site

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), interest-cohort=()"

    # Cache control for static assets
    Cache-Control = "public, max-age=31536000"

# Cache control for HTML files (shorter cache)
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# Cache control for CSS and JS files
[[headers]]
  for = "/styles/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirect rules for clean URLs and SPA behavior
[[redirects]]
  from = "/docs"
  to = "/documentation.html"
  status = 301

[[redirects]]
  from = "/documentation"
  to = "/documentation.html"
  status = 301

# Handle 404s by serving index.html (for any future SPA features)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200